server:
  port: 8080

spring:
  application:
    name: gmaildashboard

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:661777147919-vdef66d11o970j1v5o6665bjdqjagh8g.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

logging:
  level:
    org.springframework: INFO